### ISSUE TITLE
Don't turn off when charging

### ISSUE THREAD

**Issue by char101** [Magisk-Modules-Repo/blex#2]
Hi,

In my opinion the auto power off should not turn off the device if the battery level is below the configured level while the device is being charged.

The purpose of auto power off is to prevent the battery level from going below the configured level, while when the device is being charged, that condition is false because the battery level is going up. So there is no purpose in turning off the device.

**Comment by char101** [comment]
Thanks for the update. I think it is better if is_charging is checked in the same line as auto_power, i.e. only auto power off when it is not charging


```sh
      if $(auto_power) && ! is_charging; then
        if test $(batt_level) -le $(thr_power); then
          if ! poweroff; then
            setprop sys.powerctl shutdown
          fi
        fi
      fi
```

**Comment by sjayminsgithub** [comment]
Well, that's cool. But putting is_charging on another line makes it easier to find where Auto Power is handled, so I will have to disappoint you. Do you have any other stuff to share ??

**Comment by char101** [comment]
Then you can just do this

```sh
      if $(auto_power); then
        if ! is_charging; then
          if test $(batt_level) -le $(thr_power); then
            if ! poweroff; then
              setprop sys.powerctl shutdown
            fi
          fi
        fi
      fi
```

Replacing `! poweroff` with `! is_charging` has a completely different meaning because previously you are trying to run `poweroff` while now you only try to turn the device off using `setprop sys.powerctl shutdown`. Also it is unnecessary to compare the battery levels when the device is charging.

**Comment by sjayminsgithub** [comment]
Peaking through BusyBox sources, the poweroff applet itself uses `setprop sys.powerctl shutdown`, so calling that first is rather useless, and I just figured there shouldn't be any poweroff system binaries, so we don't need that applet anymore. So, if there's anything more, please tell me.

**Comment by char101** [comment]
Thanks, I have no other argument. Closing the issue.
