### ISSUE TITLE
Less brutal shutdown

### ISSUE THREAD

**Issue by terencode** [Magisk-Modules-Repo/blex#5]
Is it possible to not brutally shutdown the device (possible data corruption?) and use the regular shutdown procedure?

**Comment by sjayminsgithub** [comment]
@terencode
blex is deprecated and will be replaced by a new project identified as ACControl. This repo and the xda thread should eventually be renewed as of ACControl and not blex. I'm expecting to have ACControl ready by the end of this december, you should wait until then.

The newer project is super cool and natively implemented. You might want to track progress [here](https://github.com/sjayminsgithub/Advanced-Charging-Control).

**Comment by terencode** [comment]
@sjayminsgithub Thanks you very much for the time you took to write blex, looking forward to this new project!
